# Site settings
title: Welcome to RabbitHouse 
description: 'Business Card Page'
url: 'https://www.usagitakachi.github.io'
baseurl: ''
profilepic: '/images/kafuu-chino-cute.gif'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'UsagiCafe'
  twitter_username: makurochino
  github_username:  usagitakachi
  linkedin_username:  usagi

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
